<!-- Login form -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/';?>Login.js"></script>
<?php
$response = $this->getResponse();

if($response[0] !== null) {
?>
<div class="mt-3 alert alert-danger" role="alert">
    Error: <?= $response[0];?>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<?php } ?>

<!-- TODO CHANGE LOCALE Needed -->
<div class="container mb-5">
    <form id="form-signin" method="post">
        <h1 class="h3 mt-5 mb-3 font-weight-normal">Моля влезте.</h1>
        <div class="form-group">
            <label for="userName" >Потребителско Име</label>
            <input type="text" id="userName" name="userName" class="form-control" placeholder="User Name" required autofocus>
        </div>
        <div class="form-group">
            <label for="inputPassword" >Парола</label>
            <input type="password" name="password"  id="password" class="form-control" placeholder="Password" required>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>