<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Автосервиз</title>
    <base href="/">
    <meta http-equiv="X-UA-Compatible" content="IE=edge; IE=9; IE=8; IE=7" />
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- JQUERY! Latest compiled and minified JavaScript -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

    <!-- BOOTSTRAP! Latest compiled and minified CSS -->
    <link 
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" 
        integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" 
        crossorigin="anonymous">
    <script 
        src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" 
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" 
        crossorigin="anonymous"></script>
    <script 
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" 
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" 
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/css/font-faces.css">
    <link rel="stylesheet" href="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/css/styles.css">
    <script src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/js/functions.js"></script>
    <script>
      var URL = '<?php echo ($_SERVER['HTTPS'] !== 'off' || $_SERVER['HTTPS'] === true) ? 'https:' : 'http:'; echo OPERATOR_URL_NOPROTOCOL; ?>';
      var URL_NOPROTOCOL = '<?= OPERATOR_URL_NOPROTOCOL; ?>';
      var CURRENT_URL = URL + '/<?= $this->response['params']['params']; ?>';
    </script>
  </head>
  <body>
    <div class="container-fluid">
      <?php $this->loadPartial('navigation'); ?>
      <?php echo $this->content; ?>
    </div>
  </body>
</html>
