<!DOCTYPE html>
<html lang="en">
  <?php $this->localizeUi(array('auto_service', 'developer', 'error', 'choose', 'delete_confirmation', 'currency')); ?>
  <head>
      <!-- TODO CHANGE LOCALE Needed -->
    <title><?= $this->getUiLocaleField('auto_service'); ?></title>
    <link rel="shortcut icon" type="image/png" sizes="32x32" href="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/img/favicon-32x32.png"/>
    <base href="/">
    <meta http-equiv="X-UA-Compatible" content="IE=edge; IE=9; IE=8; IE=7" />
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- JQUERY! Latest compiled and minified JavaScript -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

    <!-- BOOTSTRAP! Latest compiled and minified CSS -->
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
            crossorigin="anonymous">
    <script 
        src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" 
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.bundle.min.js"
        integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP"
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/css/font-faces.css">
    <link rel="stylesheet" href="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/css/styles.css">
    <link rel="stylesheet" href="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/css/flags.css">

    <script src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/js/functions.js"></script>
    <script src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/js/jquery.flagstrap.min.js"></script>
    <script>
      var URL = '<?php echo (!is_null($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] !== 'off' || $_SERVER['HTTPS'] === true)) ? 'https:' : 'http:'; echo ROUTER_URL_NOPROTOCOL; ?>';
      var URL_NOPROTOCOL = '<?= ROUTER_URL_NOPROTOCOL; ?>';
      var CURRENT_URL = URL + '<?= $this->response['params']['params']; ?>';
      var AUTH_TOKEN = '<?= \App\Controller\Authenticator::$access_token; ?>';
      var LANG = '<?= \App\Router::$lang; ?>';
      var i18n = JSON.parse('<?= json_encode((object)$this->getUiLocale());?>');

    </script>
  </head>
  <body>
    <div class="container-fluid">
      <?php $this->loadPartial('navigation'); ?>
      <?php echo $this->content; ?>
      <!-- Footer -->
      <footer class="page-footer font-small bg-primary pt-4">
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">
          <p class="text-white"><?= $this->getUiLocaleField('developer'); ?></p>
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
    </div>
  </body>
</html>
