<?php $this->localizeUi(array('confirm', 'deny')); ?>

<div class="modal-footer">
  <div class="send-buttons clearfix">
    <input class=" btn btn-primary text-capitalize" type="submit"
           value="<?= $this->getUiLocaleField('confirm'); ?>" name="commit" id="submit"/>
    <button type="button" class="ml-2 btn btn-danger text-capitalize" data-dismiss="modal"
            data-toggle="modal" data-target="<?= $modalId; ?>"><?= $this->getUiLocaleField('deny'); ?></button>
  </div>
  <div hidden class="bidding-loading">
    <img src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/img/loading.gif">
  </div>
</div>