<!-- addNewColorModal -->
<div class="modal fade" id="add-new-color-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content bg-faded border-dark bidding-popup">
      <form method="post" id="add-new-client" action="#">
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container"><span class="title">Нов Цвят</span></h5>
          </div>
        </div>
        <div class="modal-body">
          <div hidden class="bidding-reason-fail alert alert-danger fade in alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <span></span>
          </div>
          <div class="form-group row clearfix">
            <label class="input-group-addon" for="color">Цвят</label>
            <input type="text" id="color" placeholder="Цвят">
          </div>
        </div>
        <div class="modal-footer">
          <div class="send-buttons clearfix">
            <input class=" btn btn-primary" type="submit" value="Потвърждавам" name="commit" id="submit"/>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Откажи</button>
          </div>
          <div hidden class="bidding-loading">
            <img src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/img/loading.gif">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>