<!-- addNewClientModal -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/'; ?>AddClient.js"></script>

<div class="modal fade" id="add-new-client-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-faded border-dark bidding-popup">
      <form method="post" id="add-new-client" action="#">
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container"><span class="title">Нов Клиент</span></h5>
          </div>
        </div>
        <div class="modal-body">
          <div class="form-group row clearfix">
            <label class="input-group-addon" for="first-name">Първо име</label>
            <input type="text"
                   id="first-name"
                   placeholder="Първо име"
                   oninvalid="this.setCustomValidity('Първото име е задължително поле.')"
                   oninput="this.setCustomValidity('')"
            >
          </div>
          <div class="form-group row clearfix">
            <label class="input-group-addon required-field" for="last-name">Фамлия</label>
            <input type="text"
                   id="last-name"
                   placeholder="Фамлия"
                   oninvalid="this.setCustomValidity('Фамилията е задължително поле.')"
                   oninput="this.setCustomValidity('')"
            >
          </div>
          <div class="form-group row clearfix">
            <label class="input-group-addon required-field" for="phone-number">Телефон</label>
            <input type="text"
                   id="phone-number"
                   placeholder="Телефон"
                   oninvalid="this.setCustomValidity('Телефонът е задължително поле.')"
                   oninput="this.setCustomValidity('')">
          </div>
        </div>
        <div class="modal-footer">
          <div class="send-buttons clearfix">
            <input class=" btn btn-primary" type="submit" value="Потвърждавам" name="commit" id="submit"/>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Откажи</button>
          </div>
          <div hidden class="bidding-loading">
            <img src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/img/loading.gif">
          </div>
        </div>
      </form>
    </div>
  </div>
  </div>