<!-- addNewBrandModelModal -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/'; ?>AddBrandModel.js"></script>

<?php $this->localizeUi(array('new_model', 'brand', 'model', 'model_name_mandatory')); ?>

<div class="modal fade" id="add-new-brand-model-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content bg-faded border-dark bidding-popup">
      <form method="post" id="add-new-brand-to-model" >
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container text-capitalize"><span class="title"><?= $this->getUiLocaleField('new_model'); ?></span></h5>
          </div>
        </div>
        <div class="modal-body">
          <div class=" form-group row clearfix">
            <label class="input-group-addon text-capitalize"><?= $this->getUiLocaleField('brand'); ?></label>
            <input type="text" disabled id="add-brand-for-model" class="text-capitalize" placeholder="<?= $this->getUiLocaleField('brand'); ?>">
            <label class="input-group-addon required-field text-capitalize" for="name"><?= $this->getUiLocaleField('model'); ?></label>
            <input type="text"
                   id="name"
                   placeholder="<?= $this->getUiLocaleField('model'); ?>"
                   oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('model_name_mandatory'); ?>.')"
                   oninput="this.setCustomValidity('')"
            >
          </div>
        </div>
        <?php $this->loadPartial('addComponent.footerModal', 'add-new-brand-model-modal'); ?>
      </form>
    </div>
  </div>
</div>