<!-- addNewBrandModal -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/'; ?>AddBrand.js"></script>

<?php $this->localizeUi(array('new_brand', 'brand', 'brand_name_mandatory')); ?>

<!-- TODO CHANGE LOCALE Needed all helpers-->
<div class="modal fade" id="add-new-brand-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog " role="document">
    <div class="modal-content bg-faded border-dark bidding-popup">
      <form method="post" id="add-new-model">
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container">
              <span class="title text-capitalize"><?= $this->getUiLocaleField('new_brand'); ?></span>
            </h5>
          </div>
        </div>
        <div class="modal-body">
          <div class="form-group row clearfix">
            <label class="col-sm-3 col-form-label text-capitalize" for="name"><?= $this->getUiLocaleField('brand'); ?></label>
              <div class="col-sm-9">
                  <input type="text"
                   id="name"
                   class="form-control text-capitalize"
                   placeholder="<?= $this->getUiLocaleField('brand'); ?>"
                   oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('brand_name_mandatory'); ?>')"
                   oninput="this.setCustomValidity('')"
            ></div>
          </div>
        </div>
          <?php $this->loadPartial('addComponent.footerModal', 'add-new-brand-modal'); ?>
      </form>
    </div>
  </div>
</div>