<!-- addNewClientModal -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/'; ?>AddClient.js"></script>

<?= $this->localizeUi(array(
    'new_client',
    'first_name',
    'last_name',
    'telephone',
    'first_name_mandatory',
    'last_name_mandatory',
    'telephone_mandatory',

));?>

<div class="modal fade" id="add-new-client-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content bg-faded border-dark bidding-popup">
      <form method="post" id="add-new-client" action="#">
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container text-capitalize">
              <span class="title"><?= $this->getUiLocaleField('new_client'); ?></span></h5>
          </div>
        </div>
        <div class="modal-body">
          <div class="form-group row clearfix">
            <label class="input-group-addon text-capitalize"
                   for="first-name"><?= $this->getUiLocaleField('first_name'); ?></label>
            <input type="text"
                   id="first-name"
                   placeholder="<?= $this->getUiLocaleField('first_name'); ?>"
                   oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('first_name_mandatory'); ?>')"
                   oninput="this.setCustomValidity('')"
            >
          </div>
          <div class="form-group row clearfix">
            <label class="input-group-addon required-field text-capitalize"
                   for="last-name"><?= $this->getUiLocaleField('last_name'); ?></label>
            <input type="text"
                   id="last-name"
                   placeholder="<?= $this->getUiLocaleField('last_name'); ?>"
                   oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('last_name_mandatory'); ?>')"
                   oninput="this.setCustomValidity('')"
            >
          </div>
          <div class="form-group row clearfix">
            <label class="input-group-addon required-field text-capitalize"
                   for="phone-number"><?= $this->getUiLocaleField('telephone'); ?></label>
            <input type="text"
                   id="phone-number"
                   placeholder="<?= $this->getUiLocaleField('telephone'); ?>"
                   oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('telephone_mandatory'); ?>')"
                   oninput="this.setCustomValidity('')">
          </div>
        </div>
        <?php $this->loadPartial('addComponent.footerModal', 'add-new-client-modal'); ?>
      </form>
    </div>
  </div>
  </div>