<!-- Automobile Modal -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/';?>AutomobilePartAddEdit.js"></script>

<?php $this->localizeUi(array(
    'price',
    'price_required',
    'name',
    'name_required',
    'spare_part',
    'part',
    'currency'
));?>

<div class="modal fade" id="add-edit-popup-modal" tabindex="-1" role="dialog" >
  <div class="modal-dialog" role="document">
    <div class="modal-content bidding-popup">
      <form method="post" id="add-edit-automobile-part" action="#">
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container"><span class="title"><?= $this->getUiLocaleField('spare_part'); ?></span></h5>
          </div>
        </div>
        <div class="modal-body">
          <div class="form-group row clearfix">
            <label class="col-sm-3 col-form-label " for="name"><?= $this->getUiLocaleField('name'); ?></label>
              <div class="col-sm-9">
              <input class="form-control"
                     type="text"
                     id="name"
                     placeholder="<?= $this->getUiLocaleField('part'); ?>"
                     required
                     oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('name_required'); ?>')"
                     oninput="this.setCustomValidity('')">
              </div>
          </div>
          <div class="form-group row clearfix">
            <label class="col-sm-3 col-form-label " for="price"><?= $this->getUiLocaleField('price'); ?></label>
              <div class="input-group col-sm-9">
                <input class="form-control"
                       type="number"
                       min="1"
                       step="any"
                       id="price"
                       placeholder="<?= $this->getUiLocaleField('price'); ?>"
                       required
                       oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('price_required'); ?>')"
                       oninput="this.setCustomValidity('')">
                  <div class="input-group-append">
                      <span class="input-group-text" ><?= $this->getUiLocaleField('currency'); ?></span>
                  </div>
              </div>
          </div>
        </div>
        <?php $this->loadPartial('addComponent.footerModal', 'add-edit-popup-modal'); ?>
        </div>
      </form>
    </div>
  </div>
</div>