<!-- Automobile Modal -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/';?>AutomobileDataAddEdit.js"></script>

<div class="modal fade" id="add-edit-popup-modal" tabindex="-1" role="dialog" >
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content bidding-popup">
      <form method="post" id="add-edit-automobile" action="#">
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container"><span class="title">Автомобил</span></h5>
          </div>
        </div>
        <div class="modal-body">
          <div hidden class="bidding-reason-fail alert alert-danger fade in alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <span></span>
          </div>
          <div class="form-group row ">
            <label class="input-group-addon ml-5" for="license_number">Регистрационен номер</label>
            <input type="text" class="rounded-right-custom border" id="license_number" placeholder="Регистрационен номер">
          </div>
          <div class="form-group row">
            <label class="input-group-addon ml-2" for="brand">Марка</label>
            <select id="brand"></select>
            <span class="btn btn-success rounded-right-custom border input-group-addon add-new-brand pointer-cursor"
                  data-toggle="modal"
                  data-target="#add-new-brand-modal">+</span>
            <label class="input-group-addon ml-3 rounded-left-custom border" for="model_id">Модел</label>
            <select id="model_id"></select>
            <span class="btn btn-success rounded-right-custom border input-group-addon add-new-brand-model pointer-cursor"
                  data-toggle="modal"
                  data-target="#add-new-brand-model-modal">+</span>
            <label class="input-group-addon ml-3 rounded-left-custom border" for="year_of_production">Година на производство</label>
            <input class="rounded-right-custom border" type="number" min="1950" max="2017" id="year_of_production">
          </div>
          <div class="form-group row clearfix">
            <label class="input-group-addon ml-2" for="engine_number">Номер на Двигател</label>
            <input class="rounded-right-custom border" type="text" id="engine_number" placeholder="Двигател">
            <span></span>
            <label class="input-group-addon ml-5 rounded-left-custom" for="vin_number">Номер на рама</label>
            <input class="rounded-right-custom border" type="text" id="vin_number" placeholder="Рама">
          </div>


          <div class="form-group row clearfix">
            <label class="input-group-addon ml-2" for="color_id">Цвят</label>
            <select id="color_id"></select>
            <span class="btn btn-success input-group-addon add-new-color pointer-cursor rounded-right-custom border"
                  data-toggle="modal"
                  data-target="#add-new-color-modal">+</span>
            <label class="input-group-addon ml-2 rounded-left-custom border" for="engine_capacity">Работен обем</label>
            <input type="number" min="0" max="9999" id="engine_capacity" placeholder="Работен обем">
            <label class="input-group-addon rounded-right-custom border" for="engine_capacity">cc</label>
            <label class="input-group-addon ml-2 rounded-left-custom border" for="owner_id">Собственик</label>
            <select id="owner_id" ></select>
            <span class="btn btn-success input-group-addon add-new-client pointer-cursor"
                    data-toggle="modal"
                    data-target="#add-new-client-modal">+</span>
          </div>
          <div class="form-group row clearfix">
            <label class="input-group-addon ml-2" for="description">Описание</label>
            <textarea id="description" class="desc-textarea rounded-right-custom border" placeholder="Описание"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <div class="send-buttons clearfix">
            <input class="btn btn-primary" type="submit" value="Потвърждавам" name="commit" id="submit"/>
            <button type="button" class="btn btn-danger" data-dismiss="modal" data-toggle="modal" data-target="add-edit-popup-modal">Откажи</button>
          </div>
          <div hidden class="bidding-loading">
            <img src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/img/loading.gif">
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<?php
$this->loadPartial('addNewClientModal');

$this->loadPartial('addNewColorModal');

$this->loadPartial('addNewBrandModal');

$this->loadPartial('addNewBrandModelModal');
?>
