<?php $response = $this->getResponse(); ?>

<div>
<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<?= OPERATOR_URL_NOPROTOCOL ; ?>">Автосервиз</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <?php if ($response['params']['params'] == 'AutomobilePart') echo 'active';?>">
        <a class="nav-link " href="<?= OPERATOR_URL_NOPROTOCOL . '/AutomobilePart'; ?>">Резервни части</a>
      </li>
      <li class="nav-item <?php if ($response['params']['params'] == 'AutomobileData') echo 'active';?>">
        <a class="nav-link" href="<?= OPERATOR_URL_NOPROTOCOL . '/AutomobileData'; ?>">Автомобили</a>
      </li>
      <li class="nav-item <?php if ($response['params']['params'] == 'RepairCardData') echo 'active';?>">
        <a class="nav-link" href="<?= OPERATOR_URL_NOPROTOCOL . '/RepairCardData'; ?>">Ремонтни карти</a>
      </li>
    </ul>
<!--    <form class="form-inline my-2 my-lg-0">-->
<!--      <input class="form-control mr-sm-2" type="text" placeholder="Search">-->
<!--      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--    </form>-->
  </div>
</nav>
</div>