<?php
$response = $this->getResponse();

$country = \App\Router::$lang === 'en' ? 'GB' : \App\Router::$lang;
?>

<nav class="navbar navbar-expand-lg navbar-toggleable-md navbar-dark bg-primary">
  <button class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <span class="navbar-brand">Автосервиз</span>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" role="tabpanel">
    <ul class="autoservice-navigation navbar-nav nav mr-auto" role="tablist">
      <li class="nav-item ">
        <a class="nav-link <?php if ($response['params']['params'] == 'AutomobilePart') echo 'active';?>" href="<?= ROUTER_URL_NOPROTOCOL . '/AutomobilePart'; ?>"
        >Резервни части</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?php if ($response['params']['params'] == 'AutomobileData') echo 'active';?>" href="<?= ROUTER_URL_NOPROTOCOL . '/AutomobileData'; ?>"
        >Автомобили</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?php if ($response['params']['params'] == 'RepairCardData') echo 'active';?>" href="<?= ROUTER_URL_NOPROTOCOL . '/RepairCardData'; ?>"
        >Ремонтни карти</a>
      </li>
    </ul>
      <div class="my-2 mr-5" >
          <div id="options" data-input-name="country" data-selected-country="<?= $country; ?>"></div>
      </div>
    <a class="btn btn-danger my-2 my-sm-0 " href="<?= ROUTER_URL_NOPROTOCOL . '/Logout'; ?>">Излез</a>
  </div>
</nav>

<script src="<?= OPERATOR_URL_NOPROTOCOL; ?>/public/js/Navbar.js"></script>