<?php $response = $this->getResponse(); ?>

<div>
<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <span class="navbar-brand">Автосервиз</span>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" role="tabpanel">
    <ul class="autoservice-navigation navbar-nav nav mr-auto" role="tablist">
      <li class="nav-item ">
        <a class="nav-link <?php if ($response['params']['params'] == 'AutomobilePart') echo 'active';?>" href="<?= OPERATOR_URL_NOPROTOCOL . '/AutomobilePart'; ?>">Резервни части</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?php if ($response['params']['params'] == 'AutomobileData') echo 'active';?>" href="<?= OPERATOR_URL_NOPROTOCOL . '/AutomobileData'; ?>">Автомобили</a>
      </li>
      <li class="nav-item">
        <a class="nav-link <?php if ($response['params']['params'] == 'RepairCardData') echo 'active';?>" href="<?= OPERATOR_URL_NOPROTOCOL . '/RepairCardData'; ?>">Ремонтни карти</a>
      </li>
    </ul>
  </div>
</nav>