<?php $response = $this->getResponse(); ?>
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/';?>RepairCardSearch.js"></script>

<form class="form-inline my-3 clearfix" id="search-form">
  <div class="form-group clearfix">
    <div class="input-group-addon" for="start_date_after">Започнат след:</div>
    <input class="search-param mr-sm-2 form-control" type="date" name="start_date_after" value="<?= $response['params']['start_date_after']; ?>" id="start_date_after">
  </div>
  <div class="form-group clearfix">
    <div class="input-group-addon" for="start_date_before">Започнат преди: </div>
    <input class="search-param mr-sm-2 form-control" type="date" name="start_date_before" value="<?= $response['params']['start_date_before']; ?>" id="start_date_before">
  </div>
  <div class="form-group clearfix">
    <label class="input-group mr-sm-2" for="automobile_id">Лицензионнен номер</label>
    <select id="automobile_id" name="automobile_id" class="search-param form-control custom-select mb-2 mr-sm-2 mb-sm-0" data-selected="<?= $response['params']['automobile_id']; ?>"></select>
  </div>
  <div class="form-group clearfix">
    <label class="custom-control custom-checkbox mb-2 mr-sm-2 mb-sm-0">
      <input type="checkbox" id="unfinished" name="unfinished" <?= $response['params']['unfinished'] == 'on' ? 'checked' : ''; ?> class="search-param custom-control-input">
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Неприключени ремонти</span>
    </label>
  </div>
  <input type="hidden" value="1" name="advanced">
  <button class="btn btn-outline-success my-2 my-sm-0 float-right" type="submit">Search</button>
</form>
