<?php
$response = $this->getResponse();

$endDateIsPresent = empty($response['params']['end_date_before']) ? false : true;

$unfinishedIsPresent =  empty($response['params']['unfinished']) ? false : true;

$unfinishedIsChecked =  $response['params']['unfinished'] == 'on' ? 'checked' : '';

$this->localizeUi(array(
    'start_date_after',
    'end_date_before',
    'license_number',
    'unfinished_repairs',
    'search'
));
?>
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/';?>RepairCardSearch.js"></script>

<form class="form-inline my-3 clearfix" id="search-form">
  <div class="form-group clearfix ml-3">
    <label class="input-group-addon mr-sm-2 text-capitalize" for="start_date_after"><?= $this->getUiLocaleField('start_date_after'); ?>:</label>
    <input class="search-param mr-sm-2 form-control"
           type="date"
           name="start_date_after"
           value="<?= $response['params']['start_date_after']; ?>"
           id="start_date_after"
    >
  </div>
  <div class="form-group clearfix ml-3">
    <label class="input-group-addon mr-sm-2 text-capitalize" for="end_date_before"><?= $this->getUiLocaleField('end_date_before'); ?>: </label>
    <input class="search-param mr-sm-2 form-control"
           type="date"
           name="end_date_before"
           <?= $unfinishedIsPresent ? 'disabled' : ''; ?>
           value="<?= $response['params']['end_date_before']; ?>"
           id="end_date_before"
    >
  </div>
  <div class="form-group clearfix ml-3">
    <label class="input-group mr-sm-2 text-capitalize" for="license_number"><?= $this->getUiLocaleField('license_number'); ?></label>
    <select id="license_number"
            name="license_number"
            class="search-param text-capitalize form-control custom-select mb-2 mr-sm-2 mb-sm-0"
            data-selected="<?= $response['params']['license_number']; ?>"></select>
  </div>
  <div class="form-group clearfix ml-3">
    <div class="custom-control custom-checkbox mb-2 mr-sm-2 mb-sm-0">
      <input type="checkbox"
             id="unfinished"
             name="unfinished"
          <?= $endDateIsPresent ? 'disabled' : ''; ?>
          <?= $unfinishedIsChecked ?>
             class="search-param custom-control-input">
      <label class="custom-control-label custom-checkbox" for="unfinished"><?= $this->getUiLocaleField('unfinished_repairs'); ?></label>
    </div>
  </div>
  <input type="hidden" value="1" name="advanced">
    <div class="form-group clearfix ml-3">
  <button class="btn btn-outline-success my-2 my-sm-0 text-capitalize float-right" type="submit"><?= $this->getUiLocaleField('search'); ?></button>
    </div>
</form>
