<?php $response = $this->getResponse(); ?>

<div class="sr-only error-message alert alert-danger alert-dismissable">
  <a class="close" aria-label="close">&times;</a>
  <span></span>
</div>

<table class="<?= $response['params']['params']; ?> table table-hover-custom table-responsive table-bordered table-striped">
  <?php $this->loadPartial('table.view.header' . \App\Router::$controllerName); ?>
  <tfoot>
    <tr>
      <td colspan="<?php if (!empty($response['data'])) echo count($response['data'][0]->getColumns()); ?>">
        <input class="btn btn-outline-success btn-lg" type="button" value="+" id="add-new"
               data-toggle="modal"
               data-target="#add-edit-popup-modal">
        <?php $this->loadPartial('pagination'); ?></td>
    </tr>
  </tfoot>
  <tbody class="row-element">
  <?php foreach ($response['data'] as $row) { ?>
    <tr class="edit-row"
        <?php foreach ($row as $key => $column) {
          echo 'data-' . $this->camelCaseToHyphen($key) . '="' . $column . '"';
        } ?>
    >
        <?php foreach ($row as $key => $column) {
            if ($key === 'id') continue; ?>
          <td class="edit-current-element <?= $key; ?>"
              data-toggle="modal"
              data-target="#add-edit-popup-modal"><?= $column; ?></td>
        <?php } ?>
        <td class="delete" align="center" valign="middle">
          <input class="btn btn-outline-danger delete-element" type="button" value="Изтрий">
        </td>
    </tr>
  <?php } ?>
  </tbody>
</table>
