<thead>
<tr>
  <th colspan="9" class="text-center">Автомобил</th>
  <th colspan="2" class="text-center">Клиент</th>
</tr>
  <tr>
    <th>Регистрационен номер</th>
    <th>Марка</th>
    <th>Модел</th>
    <th>Дата на производство</th>
    <th>Номер на двигател</th>
    <th>Номер на рама</th>
    <th>Цвят</th>
    <th>Капацитет</th>
    <th>Описание</th>
    <th>Собственик</th>
    <th>Телефон</th>
  </tr>
</thead>