<thead>
  <tr>
    <th colspan="7"  class="text-center">Карта</th>
    <th colspan="4"  class="text-center">Автомобил</th>
    <th colspan="2"  class="text-center">Клиент</th>
  </tr>
  <tr>
    <th>Номер</th>
    <th>Дата на приемане</th>
    <th>Дата на започване</th>
    <th>Дата на завършване</th>
    <th>Описание</th>
    <th>Цена</th>
    <th>Работник</th>
    <th>Регистрационен номер</th>
    <th>Марка</th>
    <th>Модел</th>
    <th>Цвят</th>
    <th>Собственик</th>
    <th>Телефон</th>
  </tr>
</thead>