<!-- Automobile Modal -->
<script src="<?= OPERATOR_URL_NOPROTOCOL . '/public/js/';?>WorkerAddEdit.js"></script>

<?php $this->localizeUi(array(
    'name_required',
    'worker',
    'first_name',
    'last_name'
));?>

<div class="modal fade" id="add-edit-popup-modal" tabindex="-1" role="dialog" >
  <div class="modal-dialog" role="document">
    <div class="modal-content bidding-popup">
      <form method="post" id="add-edit-worker" action="#">
        <div class="modal-header">
          <div class="clearfix">
            <h5 class="col-xs-6 title-container"><span class="title"><?= $this->getUiLocaleField('worker'); ?></span></h5>
          </div>
        </div>
        <div class="modal-body">
          <div class="form-group row clearfix">
            <label class="col-sm-3 col-form-label " for="first_name"><?= $this->getUiLocaleField('first_name'); ?></label>
              <div class="col-sm-9">
              <input class="form-control"
                     type="text"
                     id="first_name"
                     placeholder="<?= $this->getUiLocaleField('first_name'); ?>"
                     required
                     oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('name_required'); ?>')"
                     oninput="this.setCustomValidity('')">
              </div>
          </div>
          <div class="form-group row clearfix">
            <label class="col-sm-3 col-form-label " for="last_name"><?= $this->getUiLocaleField('last_name'); ?></label>
              <div class="input-group col-sm-9">
                <input class="form-control"
                       type="text"
                       id="last_name"
                       placeholder="<?= $this->getUiLocaleField('last_name'); ?>"
                       required
                       oninvalid="this.setCustomValidity('<?= $this->getUiLocaleField('name_required'); ?>')"
                       oninput="this.setCustomValidity('')">
              </div>
          </div>
        </div>
        <?php $this->loadPartial('addComponent.footerModal', 'add-edit-popup-modal'); ?>
        </div>
      </form>
    </div>
  </div>
</div>